### ISSUE TITLE
Navbar shifts left/right when browsing between pages with/without scrollbar

### ISSUE THREAD

**Issue by JacobJeppesen** [app-generator/django-soft-ui-design-pro#1]
Is there a way to ignore the scrollbar when determining the navbar width and position? For example, when going to https://django-soft-ui-design-pro.appseed-srv1.com/login/?next=/ , there is no scrollbar, and when logging in to the index page where there is a scrollbar, the navbar is shifted to the left. It would be great if it was possible to keep the navbar in the same place when browsing between pages with/without scroolbars.

**Comment by app-generator** [comment]
Hello @JacobJeppesen, 

Please provide an image that suggests the problem. Also, other things might help:

- Browser you're using
- Mobile or PC view 

Ty!

**Comment by JacobJeppesen** [comment]
I don't know how easy it is to see in the images below, but the scrollbar shifts the navbar (and page content) left. This makes it look a bit disturbing when browsing pages with/wihout scrollbars, and the navbar shifts left/right. One solution might be to always force a scrollbar (https://github.com/twbs/bootstrap/issues/1648). Another solution might be to use a something similar to https://stackoverflow.com/questions/65177179/how-to-move-scrollbar-behind-fixed-navbar-header (although this might make the navbar and page content unaligned).  

The issue is on PC, using any browser. Mobile views normally do not show scrollbars, so there is no issue.

![login_page](https://user-images.githubusercontent.com/19772308/154950143-add47ff5-85de-4c07-ab44-14d7d8ef04ef.png)
![logged_in](https://user-images.githubusercontent.com/19772308/154950151-e01839d8-7fd9-4eeb-a9cf-522388d717f0.jpg)

**Comment by JacobJeppesen** [comment]
I think the best solution might be to always force a scrollbar on PC. Other solutions might make the navbar and content look off-center on the page. 

So, in short, is there a way to always force a scrollbar on PC? :)

**Comment by app-generator** [comment]
The scrollbar becomes visible once the page size is bigger than the viewport.
To pass this default behavior, this solution might help:

https://www.w3schools.com/howto/howto_css_force_scrollbars.asp 

Let us know your progress.

**Comment by JacobJeppesen** [comment]
Got it working by adding `overflow-y: scroll` to `body` in the css file. The updated version is now:
```
body {
  margin: 0;
  font-family: var(--bs-font-sans-serif);
  font-size: 1rem;
  font-weight: 400;
  line-height: 1.5;
  color: #67748e;
  background-color: #fff;
  overflow-y: scroll;
  -webkit-text-size-adjust: 100%;
  -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
}
```
