### ISSUE TITLE
Applying same style to navbar and dropdown menus (semi-transparent with blur effect)

### ISSUE THREAD

**Issue by JacobJeppesen** [app-generator/django-soft-ui-design-pro#2]
The navbar is semi-transparent with a blur effect, but the dropdown menus are solid white. Is it possible to change it, such that dropdown menus have the same style as the navbar? 

An example of the current look can be seen on the screenshot below. I've tried on Chrome browser on Ubuntu 20.04.

![Screenshot from 2022-03-16 15-20-31](https://user-images.githubusercontent.com/19772308/158611291-62691dbd-d186-4e5d-81a8-5e5d4a93d01e.png)

**Comment by JacobJeppesen** [comment]
I have tried adding blur to the dropdown-menu div, which does make it transparent, but does not apply the blur effect. It might have something to do with `backdrop-filter: saturate(200%) blur(30px);` not being applied properly on the dropdown menu.

**Comment by app-generator** [comment]
Hello @JacobJeppesen, 

This customization is related to the theme core settings. A solution might be to edit the SCSS files and recompile them.

Let us know your progress.

**Comment by JacobJeppesen** [comment]
Seems like there are some issues with the implementation of the backdrop-filter in different browsers, so I'll just use solid white backgrounds for both the navbar and dropdown menus for now :)
